### ISSUE TITLE
Roubar como um artista

### ISSUE THREAD

**Issue by huogerac** [huogerac/todolist-turma1#2]
## Geral
Como criador de um produto, quero fazer uma pesquisa de ferramentas existentes e ver quais funcionalidades são interessantes e quais podem não ser uma boa ideia.

## Tarefa

Utilizar pelo menos duas das ferramentas existentes para ter uma visão geral das funcionalidades. Por exemplo, cadastrar tarefa, onde tarefas de um usuário não aparecem para os outros, listar, filtrar, categorizar etc...

👉 Utilize o comentário abaixo, para colocar sua visão de quais são as funcionalidades mais importantes para um produto que faz gestão de tarefas.

## Ferramentas existentes

- https://todoist.com/
- https://www.taskade.com/
- https://www.rememberthemilk.com/
- Pode ou não fazer parte da pesquisa: Trello e Google Keep

## Referências

- https://www.goodreads.com/book/show/44670716-a-arte-do-gaman-o
- https://www.goodreads.com/book/show/13099738-steal-like-an-artist

**Comment by julianapereiradev** [comment]
Mexendo nas ferramentas do “Todoist” e do “Taskade”, ao meu ver, as funcionalidades mais importantes para se ter um produto que faz gestão de tarefas são: Ter um título para a tarefa, espaço para descrever a tarefa, agenda (com datas e horários de cada tarefa), categorias, ordenar de acordo com as prioridades e um lembrete para o usuário realizar a tarefa.

**Comment by huogerac** [comment]
## Mapeamento parcial do Todoist

![mapeamento-todoist](https://user-images.githubusercontent.com/962233/156935459-8a3bfb04-681b-4c69-8991-7fc98378df4d.png)

## Principais funcionalidades

- Listar tarefas (filtro pela data atual)
- Filtrar por Inbox (Inbox funciona como um projeto chamado Inbox)
- Filtrar tarefas (próximas tarefas)
- Filtrar tarefas por projeto
- Mudar a ordem da listagem
- Pesquisar tarefa
- Criar projeto
- Criar seção para repartir um projeto em partes menores
- Cadastrar tarefa (o único campo obrigatório é o título da tarefa)
- Permite adicionar campos como descrição, data ou data e hora, tags e prioridade
- Permite adicionar uma tarefa dentro de um Projeto
- Permite adicionar uma tarefa dentro de uma Seção
- Permite criar sub-tarefas (hierarquia)
- Alterar qualquer atributo de uma Tarefa
- Remover uma tarefa
- Marcar tarefa como Concluída

## Outras funcinalidades

- Cadastro na plataforma (Sign Up) usando email/senha
- Cadastro na plataform usando autênticação de terceiros (Google, Facebook)
- Esqueci minha senha (qdo cadastro via email)
- Login (Sign In)
- Log Out
- Notificações
- Configurações
- Integrações com apps como google calendar
- Themas
- Histórico de ações
- Ajuda
- Programa de produtividade (Karma)

**Comment by mgrenge** [comment]
Não sei se a sugestão que vou dar vai ser viável ou relevante mas no método de gerenciamento de tarefas que eu uso (que na verdade é usando um caderno e não app) a gente faz uma diferenciação por ícones quando um tópico é uma tarefa ou um compromisso. Eu gosto disso porque me ajuda a visualizar rapidamente o que tem um horário marcado pra cumprir e o que não tem, acho que seria interessante aplicar isso. Vou colocar uma imagem pra deixar mais claro.

Ex:
[ ] Estudar CSS (tarefa)
( ) Dentista 14h30 dia 07/04 (compromisso)

![Picsart_22-03-07_23-15-59-727](https://user-images.githubusercontent.com/100451154/157153222-4d84b3fc-5833-4707-b87d-d58d26dcf918.jpg)

**Comment by huogerac** [comment]
> Não sei se a sugestão que vou dar vai ser viável ou relevante mas no método de gerenciamento de tarefas que eu uso (que na verdade é usando um caderno e não app) a gente faz uma diferenciação por ícones quando um tópico é uma tarefa ou um compromisso. Eu gosto disso porque me ajuda a visualizar rapidamente o que tem um horário marcado pra cumprir e o que não tem, acho que seria interessante aplicar isso. Vou colocar uma imagem pra deixar mais claro.
> 
> Ex: [ ] Estudar CSS (tarefa) ( ) Dentista 14h30 dia 07/04 (compromisso)
> 

Gostei destes "status", vamos pensar em como adicionar sim!

**Comment by ericksoumes** [comment]
Acredito que as funcionalidades mais importantes seria adicionar uma tarefa, agrupa-las por categorias, marcar tarefas concluídas, e ter uma visão geral das tarefas do dia e da semana. Também seria interessante estipular uma data e hora pra concluir a tarefa, assim o usuario pode receber uma notificação de quando precisa fazer aquilo (opcional).
