### ISSUE TITLE
Glossário do produto (Glossary)

### ISSUE THREAD

**Issue by huogerac** [huogerac/todolist-turma1#3]
## Visão geral

Uma boa prática para facilitar a comunicação entre os envolvidos (stackholders), é utilizar a mesma linguagem na comunicação. Desta forma a criação de um Glossário é um grande facilitador.

## Glossário

- **Tarefa**: Uma unidade de trabalho para completar um trabalho, uma atividade que será executada. Exemplo: Pagar IPTU, Jogar o lixo ou comprar uma bicicleta
- **Visitante**: Uma pessoa com acesso a internet que acessa o produto
- **Usuário**: Uma pessoa com acesso a internet que acessa o produto e cadastrou uma conta e fez login, ou seja, é um visitante que fez cadastro na plataforma
- **Mais termos relevantes para o contexto**: ?
- **Projeto ou Grupo**:  Lugar onde vamos agrupar um conjunto de tarefas, exemplos: casa, trabalho, estudos, carro, saúde etc..

## Tarefa

👉 Com a utilização das ferramentas existentes, caso alguém encontre algum termo importante para o novo produto, por favor, adicione no comentário.

**Comment by julianapereiradev** [comment]
Sincronização: Tem a finalidade de manter, de maneira simultânea, informações em dispositivos diferentes. Ou seja, ela funciona como um espelho dos arquivos, permitindo acessá-los e editá-los em dois ou mais aparelhos. (CanalTech)

(Como é o caso do Taskade que sincroniza com o Google Calendar e do Todoist que sincroniza as tarefas entre diversos dispositivos)

**Comment by huogerac** [comment]
Data finalização ou data de conclusão: Quando uma tarefa precisa ser concluída. Detalhe, um Pagar IPVA pode ter uma data como 10/jan/2022, mas uma tarefa Retorno dentista, vai ter a data: 15/fev/2022 14h30, inclusive datas não são obrigatórias

**Comment by Riverfount** [comment]
> Data finalização: Quando uma tarefa precisa ser concluída. Detalhe, um Pagar IPVA pode ter uma data como 10/jan/2022, mas uma tarefa Retorno dentista, vai ter a data: 15/fev/2022 14h30, inclusive datas não são obrigatórias

Em termos de gerenciadores de tarefas, ao menos os que eu conheço, não temos como cadastrar uma tarefa sem uma data específica!! Mas, ao mesmo tempo, achei essa ideia interessante!!

**Comment by mgrenge** [comment]
> Data finalização: Quando uma tarefa precisa ser concluída. Detalhe, um Pagar IPVA pode ter uma data como 10/jan/2022, mas uma tarefa Retorno dentista, vai ter a data: 15/fev/2022 14h30, inclusive datas não são obrigatórias

Acho que "data de conclusão" fica mais legal do que finalização
