### ISSUE TITLE
Funcionalidades desejadas (Features)

### ISSUE THREAD

**Issue by huogerac** [huogerac/todolist-turma1#4]
## Visão geral

Com base nas ferramentas existentes, tentar levantar as funcionalidades mais importantes, como categorizar tarefas como Saúde ou Trabalho, ou possibilidade de pesquisar, filtrar etc...

## Tarefa

👉 Fazer uma listagem de funcionalidades

**Comment by julianapereiradev** [comment]
* Título: Para escrever qual é a tarefa;
* Descrição: Para que o usuário possa coloca em palavras-chave assuntos relacionados àquela tarefa; 
* Data/Horário: Se a tarefa precisa ser feita hoje, amanhã, toda quarta-feira... E até que horário precisa ser feita;
* Seção: Se a tarefa se encaixa na seção trabalho, casa, saúde, etc. (se for uma seção de algum projeto específico que está sendo feito em equipe, uma funcionalidade seria compartilhar tal seção com os outros);
* Ranking: Para que o usuário veja em ordem decrescente de prioridade as tarefas a serem cumpridas;
* Lembrete: Para além do próprio site/app, acho importante ser enviado uma notificação no celular/enviar um e-mail automático para lembrar o usuário da tarefa;
* Uma barra de pesquisa: Jogar uma palavra-chave e redirecionar para a tarefa em questão cuja palavra foi menciona no título ou na descrição;
* Modo de visualização: Que o usuário tenha mais uma forma de visualizar suas tarefas (listas, colunas com cada dia da semana, mapa mental, entre outros);
* Um produto que funcione on/offline.

**Comment by eleonora-soledade** [comment]
O que mais pensei foi um jeito de simplificar e buscar objetivamente um norte prinicipal,
abaixo resumido o que pensei como prioridade

- Simplificar
- escolher 1 funcionalidade como a mais importante  - definir tarefas
- Adicionar tarefas, por dia, semana, meses, semestre e anual
- Ser avisado das tarefas pelo celular (whats, google calendar?)
- Poder compartilhar a lista de tarefas com alguém mais e designar donos das tarefas
- poder mudar tarefas de uma coluna a fazer para outra feita

**Comment by huogerac** [comment]
É normal o dono do produto querer adicionar funcionalidades "legais" no projeto, por outro lado, principalmente para o início, precisamos lembrar do **[princípio KISS](https://en.wikipedia.org/wiki/KISS_principle)**

Eu sei que o título desta tarefa é "Funcionalidades **Desejadas** e não essenciais ou extremamente necessárias! Mas de qualquer maneira, talvez um exercício é fazer a pergunta, para uma versão inicial, o produto funciona SEM ISTO? Se a resposta for SIM, podemos deixar para uma próxima entrega ... ou deixar para decedir se isto ou aquilo é realmente necessário. Decidir com base no perfil dos usuários do produto, ou seja, fazer algo o mais rápido possível, e com base no feedback, decidir o próximo passo!

É claro, pensando em protótipo, dar prazos e muitas outras coisas, é interessante entender se o produto precisa de SEÇÕES, RÓTULOS, SUB-TAREFAS.

Então nesta tarefa, o objetivo é listar dentro de todas as funcionalidades que um produto "Gerenciamento de tarefas" pode ter (conforme nosso levantamento na tarefa #2  ), quais são realmente desejadas. Okay?

## Principais funcionalidades

- ✅ Listar tarefas (filtro pela data atual)
- 🚫 Filtrar por Inbox (Inbox funciona como um projeto chamado Inbox)
- 🚫 Filtrar tarefas (próximas tarefas)
- ✅ Filtrar tarefas por projeto
- ✅ Mudar a ordem da listagem
- ✅ Pesquisar tarefa
- ✅ Criar projeto
- 🚫 Criar seção para repartir um projeto em partes menores
- ✅ Cadastrar tarefa (o único campo obrigatório é o título da tarefa)
- Permite adicionar campos como ✅ descrição, ✅ data ou ✅ data e hora, 🚫 tags e 🚫 prioridade
- ✅ Permite adicionar uma tarefa dentro de um Projeto
- 🚫 Permite adicionar uma tarefa dentro de uma Seção
- ✅ Permite criar sub-tarefas (hierarquia)
- ✅ Alterar qualquer atributo de uma Tarefa
- ✅ Remover uma tarefa
- ✅ Marcar tarefa como Concluída

## Outras funcinalidades

- ❓Cadastro na plataforma (Sign Up) usando email/senha
- ❓Cadastro na plataform usando autênticação de terceiros (Google, Facebook)
- ❓Esqueci minha senha (qdo cadastro via email)
- ✅ Login (Sign In)
- ✅ Log Out
- 🚫 Notificações
- 🚫 Configurações
- 🚫 Integrações com apps como google calendar
- 🚫 Themas
- 🚫 Histórico de ações
- 🚫 Ajuda
- 🚫 Programa de produtividade (Karma)

**Comment by huogerac** [comment]
Pessoal, com base em alguns comentários e alguns encontros que tivemos sobre este projeto, coloquei minha visão para este projeto!

Fiquem à vontade para discordar ou mostrar outro ponto de vista, tudo bem?

**Comment by cyaconquista** [comment]
Nesse projeto é interessenta ter a função de clickar e arrastar tarefas. Pois funcionalidades desse tipo agilizar para os usuarios.

**Comment by Ioboss** [comment]
Acredito que para uma primeira entrega devemos priorizar as funções essenciais.
Por exemplo:
-Tarefa
-Descrição da tarefa
-Data para executar a tarefa (com horario definido opcional)
-Lista com tarefaz finalizadas
-Barra para pesquisa da tarefa
-Ordenar as tarefas por data ou prioridade

Penso que com essas funções ja teremos uma entrega com valor e podemos ir adicionando as outras funções para refinar o projeto

**Comment by ericksoumes** [comment]
Com relação ao cadastro na plataforma eu gosto da ideia de cadastrar com a conta do Google, porque facilita a criação da conta e o acesso em outros dispositivos.
