### ISSUE TITLE
Definir a primeira funcionalidade que vamos trabalhar

### ISSUE THREAD

**Issue by huogerac** [huogerac/todolist-turma1#5]
## Visão geral

O ideial é ter um produto muito completo, com tudo funcionando e sem bugs, certo?, mas para atingir isto, pode levar-se muito tempo, desta forma, existe o conceito de fazer o mínimo possível (MVP) e validar as hipóteses o quanto antes (feedback)

## Tarefa

👉 Definir 1 ou 2 tarefas mais essenciais para iniciar a ferramenta, qual é a página mais importante? Na sua opinião, qual seria o ponto de partida? o login, cadastro de usuário, ou será que podemos iniciar a discussão de outra funcionalidade? Deixe no comentário sua opinião!

## Links / Assuntos relacionados

- https://www.ideianoar.com.br/mvp-o-que-e-minimo-produto-viavel/

**Comment by julianapereiradev** [comment]
Eu acho que um bom ponto de partida seria a Página de Login (porque tem vídeo na parte de Framework CSS que mostra isso, então a gente “começaria aos poucos” e começaria de algo que já vimos nos vídeos). 
Eu seguida, eu pensei em fazer a Página de Cadastro do Usuário (porque embaixo do login teria algo como “Não tem cadastro? Clique aqui” e essa seria a página) e, só depois disso a página principal do produto (contendo campos para digitar sua tarefa, com um menu das categorias, etc.). 

Não sei se faz muito sentido essa ordem que criei na minha cabeça... 😂😂

**Comment by LuizGuilhermePaulauskas** [comment]
Inicialmente deveríamos mesmo iniciar pelo cadastramento pois precisaremos de dados para o usuário navegar entre as tarefas, com isso o usuário cadastrado viria o login ou unificando os dois em uma página direcionando o mesmo caso não tenha cadastro e caso tenha diretamente para pagina de tarefas.  

começando a querer entender, estou meio perdido kkkkkkkk

**Comment by huogerac** [comment]
Legal pessoal, acho que todos estes pontos são válidos sim!

Poderiámos sim começar pelo cadastro de usuários, tela de login, é um ótimo exercício! Não tem nada de errado nisto!

MAS pensei em uma abordagem levemente diferente, a gente iniciar diretamente com o **epicentro** do negócio, ou seja, trabalhar no "core business" do produto. Faz sentido?

Talvez se a gente analisar, todo produto por ai tem cadastro de usuário, login etc...esta é a parte comum, se a gente "copiar" sem pensar muito, deve funcionar, certo?

Agora gastar mais energia na listagem de tarefa, os atributos e como vamos fazer a inserção de tarefas, isto sim pode fazer nosso produto diferente dos concorrentes e nos tornar reconhecidos por fazer algo de uma maneira que ninguem nunca fez! o que acham?

Desta forma e dado as funcionalidades discutidas na tarefa #4 , podemos iniciar as atividades por aqui:

## Principais funcionalidades

- 👉 **Listar tarefas (pensar na exibição, qual ordem etc...)**
-  Filtrar tarefas por projeto
-  Mudar a ordem da listagem
-  Pesquisar tarefa
-  Criar projeto
- 👉 **Cadastrar tarefa (o único campo obrigatório é o título da tarefa)**
- Permite adicionar campos como descrição,  data ou data e hora
- Permite adicionar uma tarefa dentro de um Projeto
- Alterar qualquer atributo de uma Tarefa
- Remover uma tarefa
- Marcar tarefa como Concluída

🚨 O que vocês acham? Deixe nos comentários sua visão 👀! Podem questionar ou mostrar uma opinião contrária 🎯! okay?

**Comment by marcelalpg** [comment]
Acho que poderíamos iniciar por uma tela em que daríamos foco no dia de hoje, no que a pessoa tem para fazer naquele dia. Ali, ela poderia adicionar/excluir tarefas, alterar, etc. A pessoa abriria o seu gerenciador de tarefas e já teria sua programação do dia de "hoje".
Quando ela fosse adicionar/salvar tarefas, apareceria a opção de fazer login pelo Google ou fazer seu cadastro.

**Comment by Ioboss** [comment]
> Legal pessoal, acho que todos estes pontos são válidos sim!
> 
> Poderiámos sim começar pelo cadastro de usuários, tela de login, é um ótimo exercício! Não tem nada de errado nisto!
> 
> MAS pensei em uma abordagem levemente diferente, a gente iniciar diretamente com o **epicentro** do negócio, ou seja, trabalhar no "core business" do produto. Faz sentido?
> 
> Talvez se a gente analisar, todo produto por ai tem cadastro de usuário, login etc...esta é a parte comum, se a gente "copiar" sem pensar muito, deve funcionar, certo?
> 
> Agora gastar mais energia na listagem de tarefa, os atributos e como vamos fazer a inserção de tarefas, isto sim pode fazer nosso produto diferente dos concorrentes e nos tornar reconhecidos por fazer algo de uma maneira que ninguem nunca fez! o que acham?
> 
> Desta forma e dado as funcionalidades discutidas na tarefa #4 , podemos iniciar as atividades por aqui:
> 
> ## Principais funcionalidades
> * 👉 **Listar tarefas (pensar na exibição, qual ordem etc...)**
> * Filtrar tarefas por projeto
> * Mudar a ordem da listagem
> * Pesquisar tarefa
> * Criar projeto
> * 👉 **Cadastrar tarefa (o único campo obrigatório é o título da tarefa)**
> * Permite adicionar campos como descrição,  data ou data e hora
> * Permite adicionar uma tarefa dentro de um Projeto
> * Alterar qualquer atributo de uma Tarefa
> * Remover uma tarefa
> * Marcar tarefa como Concluída
> 
> 🚨 O que vocês acham? Deixe nos comentários sua visão 👀! Podem questionar ou mostrar uma opinião contrária 🎯! okay?

Acredito que essas seriam as principais funções do projeto, para ja termos uma entrega com valor.
