### ISSUE TITLE
Protótipo & Conteúdo (Wireframes)

### ISSUE THREAD

**Issue by huogerac** [huogerac/todolist-turma1#6]
## Visão geral

É muito importante achar problemas ou falhas o quanto antes em um projeto de software, validar uma hipótese antes mesmo de fazer um código é muito mais barato de arrumar do que ter corrigir um código rodando em produção. Uma forma de fazer este exercício é através de **protótipos**, ou seja, fazemos desenhos usando papel e lápis de uma ou mais páginas, seu conteúdo! É muito fácil apagar ou mudar tudo, após mostrar para os envolvidos (stackholders) e receber sugestões/críticas.

## Tarefa

👉 Para a funcionalidade mais importante definida na tarefa #5 , desenhar um ou mais protótipos! insira sua versão nos comentários

## Importante

Existem ferramentas profissionais para fazer prototipação ou wireframes (como o [Figma](https://www.figma.com/) ), mas a ideia aqui é fazer algo simples e rápido para validar o conteúdo, não queremos gastar tempo agora aprendendo uma ferramenta de prototipação...(pelo menos não nesta etapa). Queremos não ter amor ao protótipo, para poder descartá-lo e fazer uma versão nova. Desta forma, um papel e lápis pode ser o mais indicado...

![image](https://user-images.githubusercontent.com/962233/157110508-9b06ecae-2c33-41ed-8b2e-6bf7f7b563ba.png)

**Comment by julianapereiradev** [comment]
![desafio_3_prototipo](https://user-images.githubusercontent.com/100153263/156469665-374e32bf-fc6a-4c4d-93af-05c41084062c.JPG)

Eu não sei entendi exatamente o que era para fazer nessa tarefa e como nunca fiz um protótipo no papel, não sei se está certo oq fiz hahahahha mas ficou assim:

**Comment by huogerac** [comment]
Nossa que massa @julianapereiradev 
É exatamente esta linha que temos que seguir, prototipar e tentar obter feedback! Será muito melhor desenvolver o HTML & CSS de uma página com um protótipo, revisado, refinado em mãos, não é?

Obrigado, vamos falar para o pessoal dar as opiniões! \o/

**Comment by julianapereiradev** [comment]
> Nossa que massa @julianapereiradev É exatamente esta linha que temos que seguir, prototipar e tentar obter feedback! Será muito melhor desenvolver o HTML & CSS de uma página com um protótipo, revisado, refinado em mãos, não é?
> 
> Obrigado, vamos falar para o pessoal dar as opiniões! \o/

simmm, e foi bem legal porque enquanto desenhava/fazia o rascunho iam surgindo mais ideias :D

**Comment by Riverfount** [comment]
Primeiro quero dizer que o protótipo que a @julianapereiradev fez ficou muito bom.

Agora, pensando num MVP eu focaria na principal característica do projeto, ou seja, as tarefas:

1. Como serão apresentadas?
1. Ao serem concluídas como ficarão?
1. Qual ordem elas aparecerão? Por data de conclusão? Agrupadas por categoria?
1. Teremos a vinculação das tarefas por projetos/categorias?
1. Faremos uma categorização por tags?

**Comment by mgrenge** [comment]
Parabéns @julianapereiradev, ficou muito bom! Amanhã vou tentar colocar minhas ideias no papel também

**Comment by huogerac** [comment]
> Primeiro quero dizer que o protótipo que a @julianapereiradev fez ficou muito bom.
> 
> Agora, pensando num MVP eu focaria na principal característica do projeto, ou seja, as tarefas:
> 
> 1. Como serão apresentadas?
> 2. Ao serem concluídas como ficarão?
> 3. Qual ordem elas aparecerão? Por data de conclusão? Agrupadas por categoria?
> 4. Teremos a vinculação das tarefas por projetos/categorias?
> 5. Faremos uma categorização por tags?

@Riverfount eu gosto desta linha também! Tentar primeiro pensar na página [3] da imagem acima e os itens relacionados a ela, ou seja, as regras de negócio do aplicativo de gestão de tarefa.
Talvez, as páginas de login e cadasro de usuário podem ficar para uma etapa seguinte! Faz sentido?
Desta forma, a gente poderia gerar valor na primeira entrega com a página de listar tarefas e tudo que nossa app vai fazer!

**Comment by Riverfount** [comment]
> @Riverfount eu gosto desta linha também! Tentar primeiro pensar na página [3] da imagem acima e os itens relacionados a ela, ou seja, as regras de negócio do aplicativo de gestão de tarefa.
> Talvez, as páginas de login e cadasro de usuário podem ficar para uma etapa seguinte! Faz sentido?
> Desta forma, a gente poderia gerar valor na primeira entrega com a página de listar tarefas e tudo que nossa app vai fazer!

@huogerac exatamente o que penso, por isso a relação de sugestões que coloquei na minha resposta!

**Comment by huogerac** [comment]
Pessoal, fiz alguns comentários nas Issues #2 #4 e esta forma, minha sugestão é a gente iniciar os protótipos das funcionalidades listas na tarefa #5 

O que vocês acham?

**Comment by Riverfount** [comment]
Esse foi o protótipo que fiz para a página principal do nosso APP!
![image](https://user-images.githubusercontent.com/26264782/156945746-f220597f-c8b5-4820-a846-8c082edd2673.png)

**Comment by huogerac** [comment]
Legal, você fez o HTML disto ou usou alguma ferramenta de protótipo?

A sugestão de fazer no papel, é para ser fácil de testar as coisas, por exemplo, oq acontece ao clicar no + para adicionar uma nova tarefa?
Onde aparece a data, quando a tarefa tem data?

**Comment by Riverfount** [comment]
> Legal, você fez o HTML disto ou usou alguma ferramenta de protótipo?
> 
> A sugestão de fazer no papel, é para ser fácil de testar as coisas, por exemplo, oq acontece ao clicar no + para adicionar uma nova tarefa?
> Onde aparece a data, quando a tarefa tem data?

Então usei o Figma para prototipar. Eu estava querendo fazer as demais telas tb, de inserção de nova tarefa, busca e dos ítens do menu hambúrguer, mas mano que trampo louco, no domingão foi essa tela aí mesmo!!!

**Comment by eleonora-soledade** [comment]
gente ao que vcs ja fizeram, adicionei meus rabiscos. Mas to aqui pensando como fazer isso funciona.... Por isso to pensando só em como simplificar. Tipo inserir tarefa, categorizar e avisar, já acho super complexo!!!

![navegacao](https://user-images.githubusercontent.com/98484184/157044706-d785aa73-f61d-4c61-9e75-4cbcdf078be4.jpeg)

**Comment by Marco1357** [comment]
![image](https://user-images.githubusercontent.com/58196837/157101690-e5a659a1-be95-4be2-b932-17c86c54b246.png)

**Comment by Marco1357** [comment]
Fiz uma Home do projeto no Figma

**Comment by huogerac** [comment]
> ![desafio_3_prototipo](https://user-images.githubusercontent.com/100153263/156469665-374e32bf-fc6a-4c4d-93af-05c41084062c.JPG)
> 
> Eu não sei entendi exatamente o que era para fazer nessa tarefa e como nunca fiz um protótipo no papel, não sei se está certo oq fiz hahahahha mas ficou assim:

Com base nas funcionalidades desejadas #4  e pensando nas primeiras funcionalidades, pensei em iniciar pela listagem de tarefas #5 

![protótipo-pagina-listagem-v1](https://user-images.githubusercontent.com/962233/157129907-e4f03649-69cb-4a07-8fe2-d2e379d84456.jpg)

Também tentei cobrir as funcionalidades que estão relacionadas. Como adicionar, alterar etc...

**Comment by mgrenge** [comment]
Minha contribuição

Ps: esse logo que eu fiz é só uma frescura kkk

![IMG_20220308_002825275](https://user-images.githubusercontent.com/100451154/157289711-cab27b54-15ef-4004-84c4-5ec57557f947.jpg)

**Comment by marcelalpg** [comment]
Minha contribuição. 
Ainda tenho que mexer em algumas coisas, simplificar, adicionar etc.

![PROTÓTIPO GERENCIADOR DE TAREFAS](https://user-images.githubusercontent.com/100198220/157299839-58fbec53-9cd2-4a2e-bb07-2eb8420b6d66.jpg)

**Comment by Ioboss** [comment]
Gostei bastante do prototipo da rapazeada, adicionaria uma função que nao vi de lista de tarefaz concluidas

**Comment by huogerac** [comment]
Pessoal,

Acredito que temos varias boas ideias, precisamos tentar decidir algo para a gente conseguir avancar. Senao, vamos ficar dando voltas nesta tarefa ao inves de avancar nas proximas.

Minha sugestao eh FAZER UMA VOTACAO, e ao inves de votar QUAL prototipo parece ter mais sentido, minha sugestao eh para cada um dos prototipos abaixo, a gente escrever os pontos i) pontos positivos ii) pontos negativos. E assim a gente pode conseguir chegar em um com o melhor dos mundos. O que acham?

![votacao-pagina-listagem](https://user-images.githubusercontent.com/962233/157791530-8fa5b29c-91c0-4acc-a0d0-c484fb9bd1af.jpg)

Entao, dado os 6 prototipos da pagina de LISTAR TAREFAS, oq vc mais gosta e oq menos gosta em cada um deles? se puderem listar.

**Comment by huogerac** [comment]
Pessoal, estes são alguns pontos que levantei vendo apenas a página de "Listar tarefas" dos protótipos acima.
Se puderem tentar olhar e tentar fazer uma avaliação na visão de voces, desta forma, **podemos chegar no protótipo final**.

### Protótipo 1) Feito no figma

👍 **Gostei**
- Clean e tem quase todas as funcionalidades
- Bem legal marcar o que foi feito com tachado ao invés de esconder
- Tem o conceito de projetos
- Tem um visual compacto
- Mostra o projeto

👎 **Poderia ser melhor**
- Adicionar tarefa está muito escondido
- Não sei como faço para alterar ou deletar
- Não sei como faço para ver as tarefas futuras (amanhã/próxima semana)
- É compacto, mas talvez o adicionar junto com o botao da home, pode entrar no problema de coisas distintas no mesmo lugar
- Não está claro se as tarefas vencidas também estão exibidas nas tarefas de hoje

### Protótipo 2) Laranja

👍 **Gostei**
- Da ideia de usar papel colorido 🤩

👎 **Poderia ser melhor**
- Ser menos abstrato, com uma tarefa real, mais funcionalidades
- Este tipo de protótipo pode ser muito útil no  #7 , mas não ajuda validar uma página em termos de conteúdo e funcionalidades...

### Protótipo 3) Melhor que figma

👍 **Gostei**
- Bastante detalhes, tem logo, está bem claro que é um fone
- Gostei da recorrencia na forma de `todo dia`

👎 **Poderia ser melhor**
- Falta pistas de como vou editar/excluir
- Os textos 1o ou 2o lugar, vão aparecer ou são apenas para indicar da ordanação

### Protótipo 4) Primeiro da segunda linha
- (é o meu, alguem vai precisar fazer a avaliação)

### Protótipo 5) Segundo da segunda linha
- (vou colocar em breve o que Gostei e Podeia ser melhorado)

### Protótipo 5) Último
- (vou colocar em breve o que Gostei e Podeia ser melhorado)

Valeu!

**Comment by eleonora-soledade** [comment]
Vou tentar pensar mais por etapas e analisar um por um, olhando assim vamos imaginando os passos, eu não tinha percebido as etapas da navegação antes, muito legal, mas vejo já a princípio coisas muito interessantes que poderiam ser misturadas, por exemplo:

o botão de mais para adicionar tarefas é claro e simples
ícones para categorias de tarefas que pudessem direcionar a categoria
ícones para opções das tarefas que direcionassem a essas opções de edição
tarefas recorrentes, ( todo dia)
aparecer hoje, essa semana, esse mês um embaixo do outro

**Comment by julianapereiradev** [comment]
> Pessoal,
> 
> Acredito que temos varias boas ideias, precisamos tentar decidir algo para a gente conseguir avancar. Senao, vamos ficar dando voltas nesta tarefa ao inves de avancar nas proximas.
> 
> Minha sugestao eh FAZER UMA VOTACAO, e ao inves de votar QUAL prototipo parece ter mais sentido, minha sugestao eh para cada um dos prototipos abaixo, a gente escrever os pontos i) pontos positivos ii) pontos negativos. E assim a gente pode conseguir chegar em um com o melhor dos mundos. O que acham?
> 
> ![votacao-pagina-listagem](https://user-images.githubusercontent.com/962233/157791530-8fa5b29c-91c0-4acc-a0d0-c484fb9bd1af.jpg)
> 
> Entao, dado os 6 prototipos da pagina de LISTAR TAREFAS, oq vc mais gosta e oq menos gosta em cada um deles? se puderem listar.

-- Boa tarde gente!! Tentei seguir a mesma ideia do professor na hora de escrever minhas sugestões/contribuições :D --

**1) Protótipo feito no Figma**

_Gostei:_
- De mostrar as tarefas do dia na página principal;
- Da tarefa não sumir depois de finalizada;
- De aparecer do lado de tarefa em qual categoria ela se encontra (Pessoais, trabalho, ..);
- Dos ícones criados (bem intuitivo) em especial do ícone do perfil aparecer na tela principal;
- Da palheta de cores utilizada;
- Da ideia de criar um rodapé.

_Poderia ser melhor/dúvidas:_
- Ao clicar no ícone da casa, será redirecionado para qual página? Seria essa página principal mesmo?
- (sugestão) Assim como o prof citou anteriormente, o ícone para adc a tarefa poderia ser maior. Uma ideia seria colocar na parte debaixo da tela mas no centro (para chamar mais a atenção do usuário)
- Para visualizar uma tarefa do dia seguinte, basta arrastar com o dedo para o lado ou está opção está dentro do menu?


**2) Laranja**

_Gostei:_
- Gostei que é possível ver direto na página principal não só a tarefa como também a categoria que ela se encontra;
- Colocando a legenda deu para entender direitinho do que se trata cada ícone (adicionar, procurar e compartilhar);
- Gostei da ideia de compartilhar alguma determinada tarefa/projeto com outras pessoas.

_Poderia ser melhor:_
- (sugestão) Achei que o ícone para adc a tarefa poderia ser maior. Uma ideia seria colocar na parte debaixo da tela mas no centro (para chamar mais a atenção do usuário);
- Acho que seria bom na página principal ter também uma opção/ícone para editar e excluir a tarefa.


**3) Melhor que figma**

- Esse é o meu então vou ficar aqui lendo as avaliações do colegas, mas adorei o nome que foi dado para o protótipo hahahahah


**4) Primeiro da segunda linha**

_Gostei:_
- De mostrar as tarefas da semana página principal;
- Dos ícones criados (bem intuitivo) em especial do ícone do perfil aparecer na tela principal;
- Da posição e do tamanho para o botão de adc nova tarefa;
- De ter logo na página principal as 3 bolinhas para alterar/excluir a tarefa;

_Poderia ser melhor/dúvidas:_
- (sugestão) Acho que as datas precisam aparecer mais, para o usuário abrir a página e de cara saber em que dia estamos e qual atividade precisa ser feita. Então uma sugestão seria colocar a data em cima ao invés de colocar ao lado.
- Na verdade é uma dúvida… O mesmo padrão que está na “próxima semana” (de aparecer a categoria para cada tarefa) vale também para as tarefas “dessa semana”? Porque eu acho que seria legal sempre mostrar na pág principal a categoria (saúde, trabalho, etc) de cada tarefa.


**5) Segundo da segunda linha**

_Gostei:_
- De mostrar as tarefas do dia na página principal;
- De ter um botão para olhar as tarefas dos próximos dias;
- Dos ícones criados. Achei bem legal essa ideia de diferenciar uma tarefa de um compromisso por meio dos ícones;
- Da posição e do tamanho para o botão de adc nova tarefa;
- De ter logo na página principal as 3 bolinhas para alterar/excluir a tarefa;

_Poderia ser melhor:_
- Além do usuário ver logo de cara a tarefa a ser feita e a data correspondente, acho que seria legal se aparecesse também em qual categoria ela se encontra (casa, trabalho, ..) que poderia estar abaixo ou do lado de cada uma das tarefas;
- Fiquei com uma dúvida do que seria colocado na “#tag”? Ele e o “opção de prioridade” é a mesma coisa?


**6) Último**

_Gostei:_
- De mostrar as tarefas do dia página principal;
- Dos ícones criados (bem intuitivo);
- Da posição e do tamanho para o botão de adc nova tarefa;
- De ter logo na página principal opções para alterar/excluir a tarefa;

_Poderia ser melhor/dúvidas:_
- Além do usuário ver logo de cara a tarefa a ser feita e a data correspondente, acho que seria legal se aparecesse também em qual categoria ela se encontra (casa, trabalho, ..) que poderia estar abaixo ou do lado de cada uma das tarefas;
- Fiquei com uma dúvida de qual seria a funcionalidade do ícone “visualizar tarefas”? Se eu clicar nele, o mesmo oculta todas as tarefas e ficaria vazio?

**Comment by ericksoumes** [comment]
Protótipo 1) Feito no figma

👍 Gostei

Estilo clean
Mostra as tarefas do dia na página inicial
Mostra a cadegoria ao lado da tarefa
Estilo da tarefa concluída

👎 Poderia ser melhor


Adicionar tarefa mais facilmente
Mostrar as tarefas dos próximos dias depois das de hoje
Botão para editar tarefa

Protótipo 2) Laranja

👍 Gostei

Tarefa e descrição bem clara na página inicial


👎 Poderia ser melhor

Ter um botão para adicionar tarefa e editar as existentes
Menu sanduiche para mais opções

Protótipo 3) Melhor que figma

👍 Gostei

Mostra a data de hoje e as tarefas a serem concluídas
Estão em ordem de prioridade
Mostra a categoria

👎 Poderia ser melhor

Tarefas concluídas poderia estar embaixo das ainda não concluídas
Botão de adicionar tarefa fácil

Protótipo 4) Primeiro da segunda linha

👍 Gostei

Botão para adicionar tarefa
Mostra as tarefas de hoje e da semana
Botão para editar as tarefas
Mostra a categoria ao lado

👎 Poderia ser melhor

Poderia mostrar as tarefas de hoje e as da semana separadamente

Protótipo 5) Segundo da segunda linha

👍 Gostei

Mostra as tarefas do dia na página inicial
Diferencia icone de tarefa e compromisso!!
Botão para adicionar tarefa fácil
Gostei da logo :)

👎 Poderia ser melhor

Mostrar categoria da tarefa

Protótipo 5) Último

👍 Gostei

Gostei dos icones para as funcionalidades
Box confirmando se quer mesmo excluir a tarefa
Botão adicionar tarefa fácil

👎 Poderia ser melhor

Acredito que os icones poderiam aparecer só se clicar nos 3 pontinhos ao lado por exemplo

**Comment by ericksoumes** [comment]
> Pessoal,
> 
> Acredito que temos varias boas ideias, precisamos tentar decidir algo para a gente conseguir avancar. Senao, vamos ficar dando voltas nesta tarefa ao inves de avancar nas proximas.
> 
> Minha sugestao eh FAZER UMA VOTACAO, e ao inves de votar QUAL prototipo parece ter mais sentido, minha sugestao eh para cada um dos prototipos abaixo, a gente escrever os pontos i) pontos positivos ii) pontos negativos. E assim a gente pode conseguir chegar em um com o melhor dos mundos. O que acham?
> 
> ![votacao-pagina-listagem](https://user-images.githubusercontent.com/962233/157791530-8fa5b29c-91c0-4acc-a0d0-c484fb9bd1af.jpg)
> 
> Entao, dado os 6 prototipos da pagina de LISTAR TAREFAS, oq vc mais gosta e oq menos gosta em cada um deles? se puderem listar.

Protótipo 1) Feito no figma

👍 Gostei

Estilo clean
Mostra as tarefas do dia na página inicial
Mostra a cadegoria ao lado da tarefa
Estilo da tarefa concluída

👎 Poderia ser melhor

Adicionar tarefa mais facilmente
Mostrar as tarefas dos próximos dias depois das de hoje
Botão para editar tarefa

Protótipo 2) Laranja

👍 Gostei

Tarefa e descrição bem clara na página inicial

👎 Poderia ser melhor

Ter um botão para adicionar tarefa e editar as existentes
Menu sanduiche para mais opções

Protótipo 3) Melhor que figma

👍 Gostei

Mostra a data de hoje e as tarefas a serem concluídas
Estão em ordem de prioridade
Mostra a categoria

👎 Poderia ser melhor

Tarefas concluídas poderia estar embaixo das ainda não concluídas
Botão de adicionar tarefa fácil

Protótipo 4) Primeiro da segunda linha

👍 Gostei

Botão para adicionar tarefa
Mostra as tarefas de hoje e da semana
Botão para editar as tarefas
Mostra a categoria ao lado

👎 Poderia ser melhor

Poderia mostrar as tarefas de hoje e as da semana separadamente

Protótipo 5) Segundo da segunda linha

👍 Gostei

Mostra as tarefas do dia na página inicial
Diferencia icone de tarefa e compromisso!!
Botão para adicionar tarefa fácil
Gostei da logo :)

👎 Poderia ser melhor

Mostrar categoria da tarefa

Protótipo 5) Último

👍 Gostei

Gostei dos icones para as funcionalidades
Box confirmando se quer mesmo excluir a tarefa
Botão adicionar tarefa fácil

👎 Poderia ser melhor

Acredito que os icones poderiam aparecer só se clicar nos 3 pontinhos ao lado por exemplo

**Comment by LuizGuilhermePaulauskas** [comment]
1º Protótipo  feito no figma:
  ✅ Gostei:
- Estilo clean interessante para navegação, ambiente gostoso;
- Tarefa marcada como concluída não ser apagada;
- Área de navegação intuitiva.

💡 Pontos que podem melhorar:
- Mostrar as tarefas da semana, conseguindo esconder os dias;
- Opção de alteração, inclusão ou excluir de uma tarefa.

2º Protótipo laranja:
 ✅ Gostei:
- Trabalhar com cores é muito agradável assim harmonizadas com as fontes e cores das fontes;
- Página inicial intuitiva e de fácil acesso.;
- Menu hambúrguer escondendo oque o usuário deseja.

💡 Pontos que podem melhorar:
- Utilização de uma página inicial para assim o usuário se guiar dentro dos dias da tarefa.

3º Protótipo melhor que figma:
 ✅ Gostei:
- Navegação ágil e fácil;
- Opção de clicar no menu e se orientar pra onde o usuário deseja ir;
- Bastante funcionalidade ao clicar no título da tarefa;
- Opção de ordenar as tarefas bem interessante;
- Opção de colocar em categorias de lugares para realizar as tarefas.

💡 Pontos que podem melhorar:
- Forma de mostrar tarefas concluídas;
- Botões para adicionar, editar, excluir tarefas.

4º Protótipo primeiro da segunda linha:
 ✅ Gostei:
- Mostra as tarefas da semana inteira assim conseguindo esconder dia a dia;
- Botão para editar as tarefas;
- Botão para adicionar tarefa;
- Buscar é legal caso seja um tarefa já realizada assim podendo ser adicionada novamente.

💡 Pontos que podem melhorar:
- Gosto bastante acho de fácil navegação eu usaria esse protótipo;
- Trabalharia com cores pra conseguir um ambiente gostoso ou temas seja ele o dark.
- Ícone de login poderia ser feito apenas quando estivesse em uma pagina inicial.

5º Protótipo segundo da segunda linha:
 ✅ Gostei:
- Listagem de tarefas podendo ser alterada por classes ex. mais ou menos importante alterando o ícone da tarefa;
- Adicionar tarefa fácil com o botão;

💡 Pontos que podem melhorar:
- Acredito que esta dinâmico então seguiria nesse formato.

6º Protótipo Último:
 ✅ Gostei:
- Divisões de cada item descritos na página;
- Os ícones tornam mais fácil a navegação;
- Realizar os destaques quando o usuário procura por uma tarefa o ajuda se localizar muito legal.

💡 Pontos que podem melhorar:
- Campo de pesquisa poderia ser menor pode ser apenas o ícone para seguir padrão da página;
- Campo de visualizar tarefas correspondente da semana pois já esta listada as dos dia.

**Comment by marcelalpg** [comment]
1º) Feito no figma
Gostei:
- fácil navegação;
- mostrar as tarefas do dia concluídas, por fazer e por categorias;
Poderia ser melhor:
- dar mais ênfase ao botão/ícone adicionar;
- mostrar editar e excluir tarefas;
- mostrar próximas tarefas (da semana, por exemplo).

2º) Laranja
Gostei:
- mostrar as tarefas do dia por categoria;
- compartilhar tarefas.
Poderia ser melhor:
-dar mais ênfase ao botão/ícone adicionar;
-mostrar editar e excluir tarefas;
-mostrar próximas tarefas (da semana, por exemplo).

3º) Melhor que figma
Gostei:
- bem detalhado;
- mostra as tarefas do dia por categoria e prioridade;
- fácil navegação.
Poderia ser melhor:
- a exibição dos botões adicionar tarefas, editar e excluir.
- mostrar próximas tarefas (da semana, por exemplo).

4º) Primeiro da segunda linha
Gostei:
- fácil navegação;
- ícone de perfil na tela principal;
-  mostrar as tarefas da semana e por categorias.
Poderia ser melhor:
- dar mais ênfase às tarefas do dia.

5º) Segundo da segunda linha
Gostei:;
- poder visualizar as tarefas do dia ou da semana;
- fácil navegação;
- diferenciar tarefas de compromisso.
Poderia ser melhor:
- mostrar categorias das tarefas.

6º) Terceiro da segunda linha (esse é o meu)

**Comment by huogerac** [comment]
Ahh, revisando aqui, lembrei que uma coisa interessante que deixamos passar é adicionar o "status" para uma tarefa (que a @mgrenge deu de sugestão aqui https://github.com/huogerac/todolist-turma1/issues/2#issuecomment-1061338006)

**Comment by huogerac** [comment]
Oi Pessoal,

Muito legal as contribuições, tentei ler cada ponto de cada um! Juntei tudo e assim consegui refazer o protótipo da listagem! Eu gostei do resultado do conhecimento coletivo!

**👉 Qual a opinião de vocês?**

- Conseguem ver algum problema?
- O que acharam da evolução da primeira versão até aqui?
- Podemos iniciar a implementação?
- **De 1 a 5**, o quanto claro está o que precisa ser feito? Tem ambiguidade? Tem falta de coesão? Se tiver algo confuso ou faltando, deixe no comentário...

![protótipo-pagina-listagem-v2](https://user-images.githubusercontent.com/962233/158714876-5a439e4d-d0c9-4cae-bda2-5125e3d01384.jpg)

**Comment by Marco1357** [comment]
Está bem completo com muitas funções.
Nesta fota abaixo o mesmo botão tem dupla função? Click e Hold.
![image](https://user-images.githubusercontent.com/58196837/158716979-5ef2fcd3-ac81-4a68-b018-203d2328bd74.png)

**Comment by huogerac** [comment]
> Está bem completo com muitas funções. Nesta fota abaixo o mesmo botão tem dupla função? Click e Hold. 

Sim, 
- Ao clicar (toque rápido) vai aparecer o MENU onde podemos TROCAR O ESTADO
- Ao ficar pressionando no mobile ou clicar sem soltar no desktop (HOLD/DRAG), ele permite MOVER a linha toda para cima ou para baixo, assim dando mais ou menos prioridade para a tarefa.

**Comment by julianapereiradev** [comment]
Ahh eu adorei o protótipo!! Tem um pouquinho de cada um dentro dele :) 
Muito legal ver como a primeira versão de cada um foi se complementando até chegar nesse!
Por mim, as funcionalidades do protótipo estão claras e, por isso, acredito que já podemos iniciar a implementação sim.

Só gostaria de tirar uma dúvida sobre a funcionalidade do "grupo" quando diz que "ao clicar, irá alterar o filtro para todas tarefas do grupo selecionado". No caso, se eu clico na 'Tarefa A' que tem o grupo "estudos" e mudo para o grupo "trabalho", todos os outros que tem o mesmo grupo, se alteram também?
Acho que minha dúvida na verdade está sendo quanto a definição do que seria "alterar o filtro"..

**Comment by julianapereiradev** [comment]
> Oi Pessoal,
> 
> Muito legal as contribuições, tentei ler cada ponto de cada um! Juntei tudo e assim consegui refazer o protótipo da listagem! Eu gostei do resultado do conhecimento coletivo!
> 
> **point_right Qual a opinião de vocês?**
> 
> * Conseguem ver algum problema?
> * O que acharam da evolução da primeira versão até aqui?
> * Podemos iniciar a implementação?
> * **De 1 a 5**, o quanto claro está o que precisa ser feito? Tem ambiguidade? Tem falta de coesão? Se tiver algo confuso ou faltando, deixe no comentário...
> 
> ![protótipo-pagina-listagem-v2](https://user-images.githubusercontent.com/962233/158714876-5a439e4d-d0c9-4cae-bda2-5125e3d01384.jpg)

Ahh eu adorei o protótipo!! Tem um pouquinho de cada um dentro dele :)
Muito legal ver como a primeira versão de cada um foi se complementando até chegar nesse!
Por mim, as funcionalidades do protótipo estão claras e, por isso, acredito que já podemos iniciar a implementação sim.

Só gostaria de tirar uma dúvida sobre a funcionalidade do "grupo" quando diz que "ao clicar, irá alterar o filtro para todas tarefas do grupo selecionado". No caso, se eu clico na 'Tarefa A' que tem o grupo "estudos" e mudo para o grupo "trabalho", todos os outros que tem o mesmo grupo, se alteram também?
Acho que minha dúvida na verdade está sendo quanto a definição do que seria "alterar o filtro"..

**Comment by huogerac** [comment]
> Só gostaria de tirar uma dúvida sobre a funcionalidade do "grupo" quando diz que "ao clicar, irá alterar o filtro para todas tarefas do grupo selecionado". No caso, se eu clico na 'Tarefa A' que tem o grupo "estudos" e mudo para o grupo "trabalho", todos os outros que tem o mesmo grupo, se alteram também?
> Acho que minha dúvida na verdade está sendo quanto a definição do que seria "alterar o filtro"..

O que imaginei foi:
Quando estamos na listagem inicial, por exemplo, todas tarefas vencendo hoje. 1) vai listar apenas tarefas com vencidas ou com vencimento para hoje 2) vai ter tarefas independente do seu grupo
Desta forma, vamos pensar que temos tarefas do grupo saúde e do grupo estudos, ao clicar no grupo estudos, o filtro será alterado para listar todas tarefas (independente se está vencida ou não e mesmo as que não tem data), porém filtrando tudo do grupo estudo.
É o mesmo efeito do todoist, quando selecionamos o "Projeto", onde vai listar todas tarefas do projeto selecionado...
Faz sentido?

**Comment by julianapereiradev** [comment]
> > Só gostaria de tirar uma dúvida sobre a funcionalidade do "grupo" quando diz que "ao clicar, irá alterar o filtro para todas tarefas do grupo selecionado". No caso, se eu clico na 'Tarefa A' que tem o grupo "estudos" e mudo para o grupo "trabalho", todos os outros que tem o mesmo grupo, se alteram também?
> > Acho que minha dúvida na verdade está sendo quanto a definição do que seria "alterar o filtro"..
> 
> O que imaginei foi: Quando estamos na listagem inicial, por exemplo, todas tarefas vencendo hoje. 1) vai listar apenas tarefas com vencidas ou com vencimento para hoje 2) vai ter tarefas independente do seu grupo Desta forma, vamos pensar que temos tarefas do grupo saúde e do grupo estudos, ao clicar no grupo estudos, o filtro será alterado para listar todas tarefas (independente se está vencida ou não e mesmo as que não tem data), porém filtrando tudo do grupo estudo. É o mesmo efeito do todoist, quando selecionamos o "Projeto", onde vai listar todas tarefas do projeto selecionado... Faz sentido?

Ahhh entendi agora e faz total sentido!
